### PR TITLE
Build pool libs as shared if umf is shared also

### PR DESCRIPTION
**Pull request by bratpiorka**
### Description

Build memory pool libs (disjoint, scalable, etc.) as shared if the main libumf is also built as shared lib.

Ref: #387

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

### CODE REVIEW

**Comment by vinser52** [comment]
> Build memory pool libs (disjoint, scalable, etc.) as shared if the main libumf is also built as shared lib.

What is the reason for that?

**Comment by bratpiorka** [comment]
> > Build memory pool libs (disjoint, scalable, etc.) as shared if the main libumf is also built as shared lib.
> 
> What is the reason for that?

I think we should either provide all libs as shared objects or none. Please think about what we will install in oneAPI toolkit. The discussion is here: https://github.com/oneapi-src/unified-memory-framework/issues/387

**Comment by vinser52** [comment]
> I think we should either provide all libs as shared objects or none. Please think about what we will install in oneAPI toolkit. The discussion is here: https://github.com/oneapi-src/unified-memory-framework/issues/387

Ok, I have replied to the discussion thread #387.

**Comment by bratpiorka** [comment]
closing this as we agreed in #387. that we don't want this change

**Pull request closed without merging**
