### PR TITLE
WIP: pool memory resource that can be used with an upstream memory resource

### PR DESCRIPTION
**Pull request by igchor**

### CODE REVIEW

**Comment by vinser52** [comment]
Some general question:
On the last WG meeting we agreed that we do not need to implement memory resources on top of UMF (at least not now), correct? Instead we are discussing to have memory resource implementation on top of SYCL.
So why do we need this PR?

**Comment by igchor** [comment]
@vinser52 that's correct, I just want to have something I can use for benchmarking/testing once we have the SYCL provider and different pool implementations (jemalloc). This PR just exposes some simple abstractions to build a pool memory_resource. I don't plan to have it merged for now. Would you prefer if I just kept it on a separate branch and not have the PR open?

**Comment by vinser52** [comment]
Thank you for your clarifications.

> Would you prefer if I just kept it on a separate branch and not have the PR open?

Keeping it in a separate fork is OK. Regarding the branch instead of the fork do you mean creating a separate branch in this repo? Regarding PR, what is your intention by opening the PR? If you need a review than it totally makes sense and we can keep this PR and review/discuss the code.

**Comment by igchor** [comment]
My intention was just to have this visible so I can reference this PR when discussing the SYCL provider, show some examples, etc.

**Comment by bratpiorka** [comment]
outdated

**Pull request closed without merging**
