### PR TITLE
Fix: make it possible to allocate more than initial pool size

### PR DESCRIPTION
**Pull request by ldorau**
Make it possible to allocate more than the initial pool size of the linear allocator.
It fixes a serious bug leading to a segfault in the linear base allocator.

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
do we have any test for that? 😉

**Comment by bratpiorka** [comment]
> do we have any test for that? 😉

agree - please add a test that creates 1000 providers / pools :)

**Comment by ldorau** [comment]
> do we have any test for that? 😉

@lukaszstolarczuk A test added.
Done.

**Comment by ldorau** [comment]
> > do we have any test for that? 😉
> 
> agree - please add a test that creates 1000 providers / pools :)

A test added.
Done.

**Review by bratpiorka — APPROVED** [review]

**Review by lukaszstolarczuk — COMMENTED** [review]
👍

**Review by igchor — APPROVED** [review]

**Pull request merged**
