### PR TITLE
fix: substitute UT_ASSERTs with asserts from GTEST part last

### PR DESCRIPTION
**Pull request by EuphoricThinking**
Amen.

ref. #569

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

- [ ] CI workflows, not executed per PR (e.g. Nightly), execute properly 
- [ ] New tests added, especially if they will fail without my changes
- [ ] Added/extended example(s) to cover this functionality
- [ ] Extended the README/documentation
- [ ] All newly added source files have a license
- [ ] All newly added source files are referenced in CMake files
- [ ] Logger (with debug/info/... messages) is used

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]
... and let's never speak of this again.

Might be useful to remove [all these asserts](https://github.com/oneapi-src/unified-memory-framework/blob/7ed878716bfaa76067d542d947a03b1de9a6ceac/test/common/test_helpers.h#L25-L76) entirely.

**Comment by EuphoricThinking** [comment]
> Might be useful to remove [all these asserts](https://github.com/oneapi-src/unified-memory-framework/blob/7ed878716bfaa76067d542d947a03b1de9a6ceac/test/common/test_helpers.h#L25-L76) entirely.

These asserts are used in .c files in test/c_api, since GTEST is C++ framework

**Review by lukaszstolarczuk — APPROVED** [review]

**Comment by pbalcer** [comment]
> > Might be useful to remove [all these asserts](https://github.com/oneapi-src/unified-memory-framework/blob/7ed878716bfaa76067d542d947a03b1de9a6ceac/test/common/test_helpers.h#L25-L76) entirely.
> 
> These asserts are used in .c files in test/c_api, since GTEST is C++ framework. Do you mean replacing using another framework?

I'm a bit worried that this same issue will creep up again. No, using another framework just for the C api isn't worth it.

One option would be to rewrite those tests to use gtest. At first I thought this was done without gtestso that it's possible to compile and test this with a C compiler. But, looking at CMake's, it looks as if all the tests are compiled the same way.

Alternatively, we could move those test_helpers into the `c_api` directory to make sure it's not possible to use those C-like asserts in the C++ part of the codebase.

**Review by vinser52 — APPROVED** [review]

**Comment by lplewa** [comment]
> > > Might be useful to remove [all these asserts](https://github.com/oneapi-src/unified-memory-framework/blob/7ed878716bfaa76067d542d947a03b1de9a6ceac/test/common/test_helpers.h#L25-L76) entirely.
> > 
> > 
> > These asserts are used in .c files in test/c_api, since GTEST is C++ framework. Do you mean replacing using another framework?
> 
> I'm a bit worried that this same issue will creep up again. No, using another framework just for the C api isn't worth it.
> 
> One option would be to rewrite those tests to use gtest. At first I thought this was done without gtest so that it's possible to compile and test this with a C compiler. But, looking at CMake's, it looks as if all the tests are compiled the same way.
> 
> Alternatively, we could move those test_helpers into the `c_api` directory to make sure it's not possible to use those C-like asserts in the C++ part of the codebase.

There is few IPC tests which are implemented without gtest as they require multiple processes. So we cannod rid of those UTASSERTS

**Review by lplewa — APPROVED** [review]

**Pull request merged**
