### PR TITLE
[CI] Enable multi-numa workflow on RHEL

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] Enable self-hosted runner RHEL
- [x] Code compiles without errors locally
- [x] All tests pass locally
- [x] CI workflows execute properly

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]

**Comment by bratpiorka** [comment]
do we want to test RHEL only on MultiNuma workflow?

**Comment by lukaszstolarczuk** [comment]
> do we want to test RHEL only on MultiNuma workflow?

It actually runs all the tests - I used this workflow, because it uses self-hosted runners and the machine has multiple numa nodes.

**Review by ldorau — APPROVED** [review]

**Comment by ldorau** [comment]
@lukaszstolarczuk Have you seen this?
https://github.com/oneapi-src/unified-memory-framework/actions/runs/9615506820/job/26588167848?pr=561
```
[  SKIPPED ] 8 tests, listed below:
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/0
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/1
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/2
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/3
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/4
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/5
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/6
[  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/7
```
Is it OK?

**Comment by lukaszstolarczuk** [comment]
> @lukaszstolarczuk Have you seen this (on [MultiNuma / rhel-9.1](https://github.com/oneapi-src/unified-memory-framework/actions/runs/9615506820/job/26588167848?pr=561#logs))? https://github.com/oneapi-src/unified-memory-framework/actions/runs/9615506820/job/26588167848?pr=561
> 
> ```
> [  SKIPPED ] 8 tests, listed below:
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/0
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/1
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/2
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/3
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/4
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/5
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/6
> [  SKIPPED ] checkModeSplit/testNumaSplit.checkModeSplit/7
> ```
> 
> Is it OK that these tests are skipped?

yeah, these are tests requiring 3 numa nodes and this machine only has 2. I confirmed this with author of these tests - it's ok.

**Comment by ldorau** [comment]
> > Is it OK that these tests are skipped?
> 
> yeah, these are tests requiring 3 numa nodes and this machine only has 2. I confirmed this with author of these tests - it's ok.
>

OK

**Review by ldorau — APPROVED** [review]

**Pull request merged**
