### PR TITLE
Get size from tracking provider in proxy_free()

### PR DESCRIPTION
**Pull request by ldorau**
### Description

Get size from tracking provider in `proxy_free()`.

Fixes: #475

### Checklist
- [x] Code compiles without errors locally
- [x] All tests pass locally
- [x] CI workflows execute properly

### CODE REVIEW

**Comment by lplewa** [comment]
Do it fix #475 ? 

IF you build umf without tracking provider there is still an issue

**Comment by vinser52** [comment]
> IF you build umf without tracking provider there is still an issue

There is PR #485 which removes the option to build YMF without a memory tracker. As I mentioned before, many features in UMF became dependent on memory tracking functionality. Therefore, I believe there are no reasons to disable it at build time, but it is still possible to disable memory tracking capabilities for a particular pool.

**Comment by ldorau** [comment]
> Do it fix #475 ?
> 
> IF you build umf without tracking provider there is still an issue

@lplewa see #485

**Comment by ldorau** [comment]
#485 has been merged

**Review by vinser52 — APPROVED** [review]

**Pull request merged**
