### PR TITLE
Minor fixes to clean up resources in tests

### PR DESCRIPTION
**Pull request by vinser52**
### Description
Minor fixes to properly clean up resources when disjoint pool params functions return an error. 

### Checklist

- [x] Code compiles without errors locally
- [x] All tests pass locally
- [ ] CI workflows execute properly

### CODE REVIEW

**Review by ldorau — APPROVED** [review]

**Comment by lplewa** [comment]
why valgrind did not detect this issue? @ldorau ?

**Review by lplewa — APPROVED** [review]

**Review by lukaszstolarczuk — APPROVED** [review]

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
actually, shouldn't this go to v0.10.x ...?

**Comment by bratpiorka** [comment]
> actually, shouldn't this go to v0.10.x ...?

this is not needed there as this only fixes tests - there is no bug in Disjoint Pool implementation

**Comment by vinser52** [comment]
I think it is not needed for `0.10`. It is even was not detected by Coverity. I found this minor issue when investigated Coverity issue and looked through the code, but it was not reported by Coverity.

**Comment by vinser52** [comment]
@bratpiorka what is your final answer, should I switch target branch to `0.10` or will we merge just to the main?

**Comment by lukaszstolarczuk** [comment]
ok, that's perferct, if not found by the coverity tool, then it's ok

**Review by lukaszstolarczuk — APPROVED** [review]

**Pull request merged**
