### PR TITLE
Revert moving `free()` to optional (ext) provider ops

### PR DESCRIPTION
**Pull request by ldorau**
### Description

Revert moving `free()` to optional (ext) provider ops.

This reverts commit b0bfbb7e92b76cc56c3bcd91c7ac063467136376.

Remove `umfDefaultFree()` and `umfIsFreeOpDefault()`.

Remove the `disable_upstream_provider_free` parameter
of the Coarse provider.

Remove the `upstreamDoesNotFree` argument of
the `umfTrackingMemoryProviderCreate()` function.

Requires:
- [x] #932 

### Checklist

- [x] Code compiles without errors locally
- [x] All tests pass locally
- [x] CI workflows execute properly

### CODE REVIEW

**Comment by ldorau** [comment]
@bratpiorka @vinser52 please review

**Review by KFilipek — APPROVED** [review]

**Review by vinser52 — APPROVED** [review]

**Comment by vinser52** [comment]
@bratpiorka  I think it should be part of the `0.10`

**Comment by ldorau** [comment]
> @bratpiorka I think it should be part of the `0.10`

@vinser52 Are you sure? This change requires `libcoarse` which is not present in `0.10` ...

**Comment by vinser52** [comment]
> > @bratpiorka I think it should be part of the `0.10`
> 
> @vinser52 Are you sure? This change requires `libcoarse` which is not present in `0.10` ...

We are changing interfaces, the earlier we do that -> less impact for the future users. 

Regarding `libcoarse`, does it impact only file and devdax providers? Can we merge the `libcoarse` to the 0.10?

**Comment by ldorau** [comment]
> Regarding `libcoarse`, does it impact only file and devdax providers?

Yes, only file and devdax providers.

**Comment by bratpiorka** [comment]
@vinser52 @ldorau devdax and file providers would not be used in 0.10x and I prefer to minimize the number of changes there at least right now. If we know that there are no major problems with 0.10x, then we could think about merging changes related to the coarse lib (this is a lot of code and multiple PRs).

**Pull request merged**
