### PR TITLE
Add SLES15 to multi-NUMA C

### PR DESCRIPTION
**Pull request by bieszk01**
SLES15 support

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
If it is just for testing then you should:
1) convert this PR to draft (since it is not read yet)
2) use a temporary patch like https://github.com/ldorau/unified-memory-framework/commit/a590c27dfe8fdb98930da37dc29dbb158487edff on my `DEBUG_CI_run_only_multi_numa` branch to test only one CI job that you are changing and do not occupy other resources, when you do not need them (the resources in public UMF CI are very limited).

**Comment by ldorau** [comment]
The description of the commit did not change:
image

**Comment by ldorau** [comment]
Please do NOT submit a new PR for each new version of your PR, just push with `--force` on the same branch to update the current PR

**Comment by bieszk01** [comment]
> Please do NOT submit a new PR for each new version of your PR, just push with `--force` on the same branch to update the current PR

I user only github's web page for operations :)

**Comment by ldorau** [comment]
> > Please do NOT submit a new PR for each new version of your PR, just push with `--force` on the same branch to update the current PR
> 
> I use only github's web page for operations :)

So please use the git CLI in the terminal.

**Comment by ldorau** [comment]
The SLES15 build did not start: https://github.com/oneapi-src/unified-memory-framework/actions/runs/12373611621/job/34537021263
Please apply the temporary patch: https://github.com/ldorau/unified-memory-framework/commit/a590c27dfe8fdb98930da37dc29dbb158487edff to test only this one workflow

**Comment by ldorau** [comment]
It look like you did not started the GHA runner on the SLES15 machine, maybe ?

**Pull request closed without merging**
