### PR TITLE
Use base allocator in the OS provider

### PR DESCRIPTION
**Pull request by ldorau**

### CODE REVIEW

**Comment by ldorau** [comment]
What about:
```c
            hwloc_bitmap_list_asprintf(&strp, nodeset);
            free(strp);
```
?

**Comment by ldorau** [comment]
Fixes of error handling submitted in #211

**Comment by bratpiorka** [comment]
> ```c
>             hwloc_bitmap_list_asprintf(&strp, nodeset);
>             free(strp);
> ```

hwloc uses malloc: 
https://github.com/open-mpi/hwloc/blob/eeeda4ad2d0511a2334a02141dab6138b1e0ce47/hwloc/bitmap.c#L480C9-L480C15

@igchor maybe we should use hwloc only for topo discovery which is not needed in OS provider?

**Comment by ldorau** [comment]
`hwloc_topology_init()` can also use `malloc()`:
https://github.com/open-mpi/hwloc/blob/master/hwloc/topology.c#L3853

**Comment by ldorau** [comment]
> > ```c
> >             hwloc_bitmap_list_asprintf(&strp, nodeset);
> >             free(strp);
> > ```
> 
> hwloc uses malloc: https://github.com/open-mpi/hwloc/blob/eeeda4ad2d0511a2334a02141dab6138b1e0ce47/hwloc/bitmap.c#L480C9-L480C15
> 
> @igchor maybe we should use hwloc only for topo discovery which is not needed in OS provider?

@bratpiorka @igchor I think it is a separate issue for a separate PR and this PR can be merged without fixing this issue.

**Comment by bratpiorka** [comment]
> > > ```c
> > >             hwloc_bitmap_list_asprintf(&strp, nodeset);
> > >             free(strp);
> > > ```
> > 
> > 
> > hwloc uses malloc: https://github.com/open-mpi/hwloc/blob/eeeda4ad2d0511a2334a02141dab6138b1e0ce47/hwloc/bitmap.c#L480C9-L480C15
> > @igchor maybe we should use hwloc only for topo discovery which is not needed in OS provider?
> 
> @bratpiorka @igchor I think it is a separate issue for a separate PR and this PR can be merged without fixing this issue.

agree

**Review by bratpiorka — APPROVED** [review]

**Review by PatKamin — APPROVED** [review]

**Pull request merged**
