### PR TITLE
[tests] Fix: Use of auto that causes a copy

### PR DESCRIPTION
**Pull request by KFilipek**
Coverity CID: 436575

### CODE REVIEW

**Review by kswiecicki — APPROVED** [review]

**Comment by bratpiorka** [comment]
could you change the commit message to "add const to an auto type to prevent from calling copy constructor" or something like that?

**Comment by KFilipek** [comment]
> could you change the commit message to "add const to an auto type to prevent from calling copy constructor" or something like that?

Fixed:
`[tests] Fix: add const & to prevent calling copy constructor`

**Comment by igchor** [comment]
@ldorau base_alloc_linear test seems to be failing, could you take a look? (https://github.com/oneapi-src/unified-memory-framework/actions/runs/8020268125/job/21911573318?pr=255)

**Review by lukaszstolarczuk — COMMENTED** [review]
👍

**Review by vinser52 — APPROVED** [review]

**Pull request merged**
