### PR TITLE
Enable drd and helgrind in the valgrind jobs

### PR DESCRIPTION
**Pull request by ldorau**
Enable drd and helgrind in the valgrind jobs.

Fixes: #156
Fixes: #157

### CODE REVIEW

**Comment by igchor** [comment]
Do we actually want to run drd and helgrind tests? We already have tsan which cover most (I think) of the things checked by drd/helgrind and tsan has better support for the standard library. Also, it seems that it does not report any false positives for jemalloc/tbb.

**Review by lukaszstolarczuk — COMMENTED** [review]
~~pls add a link to your execution of this or possibly run this workflow on `push` trigger to see the output~~

nevermind, I didn't see your prev. PR enabling Valgrind on PR.

**Comment by ldorau** [comment]
> ~pls add a link to your execution of this or possibly run this workflow on `push` trigger to see the output~
> 
> nevermind, I didn't see your prev. PR enabling Valgrind on PR.

So is it OK now ?

**Comment by ldorau** [comment]
> ~pls add a link to your execution of this or possibly run this workflow on `push` trigger to see the output~
> 
> nevermind, I didn't see your prev. PR enabling Valgrind on PR.

@lukaszstolarczuk So is it OK now ?

**Comment by ldorau** [comment]
Rebased

**Review by kswiecicki — APPROVED** [review]

**Review by bratpiorka — APPROVED** [review]

**Comment by igchor** [comment]
I think there is some problem with the script. When I run test_valgrind.sh everything is reported as "PASSED" but when I run valgrind manually (valgrind --tool=memcheck ./test/umf_test-jemalloc_pool) then it reports errors without the suppresions.

**Review by igchor — CHANGES_REQUESTED** [review]
Please verify that the script works correctly. Valgrind still fails on my machine.

**Comment by ldorau** [comment]
@igchor the script works correctly now

**Review by igchor — APPROVED** [review]

**Comment by igchor** [comment]
> @igchor could you confirm?

Yes, it looks good now. The tests fail without the suppressions as expected.

**Pull request merged**
