### PR TITLE
Do not check coverage in the Release multi-numa build

### PR DESCRIPTION
**Pull request by ldorau**
### Description

1) Do not check coverage in the Release multi-numa build
2) Unify the name of the coverage data file in the `upload-artifact`
   step and the coverage artifact file in the `Check coverage` step.
   A name of the coverage artifact file in the `Check coverage` step
   must be unique.

### Checklist

- [x] Code compiles without errors locally
- [x] All tests pass locally
- [x] CI workflows execute properly

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
is it really a fix - was something broken? or just a cleanup in the names?

**Comment by bratpiorka** [comment]
> is it really a fix - was something broken? or just a cleanup in the names?

fix for sporadic fails like here
https://github.com/oneapi-src/unified-memory-framework/actions/runs/12214905680/job/34076621998?pr=898

**Comment by ldorau** [comment]
> is it really a fix - was something broken? or just a cleanup in the names?

@lukaszstolarczuk This patch fixes the regression introduced by the commits: 9d23a57a799458d22ccc6ee31ba937ee6fc3f6c3 and 2a7a22943584842bfc5e4f54e208e19fb469fa0c.

**Comment by lukaszstolarczuk** [comment]
och, I see you updated the PR now with extra `if debug` in multinuma, which makes sense.

For GPU workflow it's still a name change only, right?

**Comment by ldorau** [comment]
> och, I see you updated the PR now with extra `if debug` in multinuma, which makes sense.
> 
> For GPU workflow it's still a name change only, right? no fix in "logic" needed?

No, in both cases it is a fix for the regression introduced by the commits: https://github.com/oneapi-src/unified-memory-framework/commit/9d23a57a799458d22ccc6ee31ba937ee6fc3f6c3 and https://github.com/oneapi-src/unified-memory-framework/commit/2a7a22943584842bfc5e4f54e208e19fb469fa0c because the name of the coverage data file in the `upload-artifact` step must be exactly the same like `$COVERAGE_FILE_NAME` in the `Check coverage` step where this file is generated.

**Comment by ldorau** [comment]
CI builds passed: https://github.com/oneapi-src/unified-memory-framework/actions/runs/12231973390
I have updated only the commit's description.

**Comment by ldorau** [comment]
@bratpiorka @lukaszstolarczuk please review

**Review by bratpiorka — APPROVED** [review]

**Comment by lukaszstolarczuk** [comment]
> No, in both cases it is a fix for the regression introduced by the commits: [9d23a57](https://github.com/oneapi-src/unified-memory-framework/commit/9d23a57a799458d22ccc6ee31ba937ee6fc3f6c3) and [2a7a229](https://github.com/oneapi-src/unified-memory-framework/commit/2a7a22943584842bfc5e4f54e208e19fb469fa0c) because the name of the coverage data file in the `upload-artifact` step must be exactly the same like `$COVERAGE_FILE_NAME` in the `Check coverage` step where this file is generated.

heh, ok, thanks for clarification. The 2 commits you mentioned, introduced many changes, without the description it didn't tell me much.

So now:
1. why not use the actual variable `COVERAGE_FILE_NAME`? we already have it composed, don't compose it for the second time, perhaps?
2. (optional) why did it fail only randomly and sporadically? when the 2 commits were introduced they did not introduce lower coverage score...

**Comment by lukaszstolarczuk** [comment]
@ldorau, please change the base branch to the v0.10.x

**Review by KFilipek — APPROVED** [review]

**Comment by ldorau** [comment]
> @ldorau, please change the base branch to the v0.10.x

Done

**Comment by ldorau** [comment]
> 1. why not use the actual variable `COVERAGE_FILE_NAME`? we already have it composed, don't compose it for the second time, perhaps?

@lukaszstolarczuk Done

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
just one thing to confirm yet - I also added CONFIG_NAME in QEMU run_test.sh and it does not match with then name used in workflow (it contains multiple configs per 1 OS)

**Comment by ldorau** [comment]
> just one thing to confirm yet - I also added CONFIG_NAME in QEMU run_test.sh and it does not match with then name used in workflow (it contains multiple configs per 1 OS)

It is OK. 
I have checked it again and it turned out that in fact those names does not have to be the same - they have to be only unique and the coverage directories have to contain non-empty coverage data files.

**Pull request merged**
