### PR TITLE
Fuzz test fixes

### PR DESCRIPTION
**Pull request by lplewa**
Fixes in fuzz test - details on commits messages.

### CODE REVIEW

**Review by bratpiorka — APPROVED** [review]

**Comment by PatKamin** [comment]
`remote` -> `remove` in commit msgs.

Why are you removing all these prints? How can you determine the scenario (generated API calls) on a test fail with all prints removed?

**Comment by lplewa** [comment]
> `remote` -> `remove` in commit msgs.
> 
> Why are you removing all these prints? How can you determine the scenario (generated API calls) on a test fail with all prints removed?

read sed from log, and reproduce it

**Comment by bratpiorka** [comment]
> `remote` -> `remove` in commit msgs.
> 
> Why are you removing all these prints? How can you determine the scenario (generated API calls) on a test fail with all prints removed?

because the logs produced by this test hangs chrome :) also, the zip with logs > 50 MB

**Comment by PatKamin** [comment]
> > `remote` -> `remove` in commit msgs.
> > Why are you removing all these prints? How can you determine the scenario (generated API calls) on a test fail with all prints removed?
> 
> read seed from log, and reproduce by using it.

Should work, ok

**Review by PatKamin — APPROVED** [review]

**Review by kswiecicki — APPROVED** [review]

**Review by lukaszstolarczuk — APPROVED** [review]

**Pull request merged**
