### PR TITLE
Enable OS provider in builds in the include section

### PR DESCRIPTION
**Pull request by ldorau**
Enable OS provider in builds in the include section. All variables have to be set explicitly in the include section. The values set in the matrix section are NOT copied to the include section.

### CODE REVIEW

**Comment by ldorau** [comment]
@PatKamin OS memory provider config tests are failing:
https://github.com/ldorau/unified-memory-framework/actions/runs/7668075936/job/20899263459
https://github.com/ldorau/unified-memory-framework/actions/runs/7668648729/job/20900907971
@PatKamin could you take a look at this?

**Comment by igchor** [comment]
@ldorau can you try rebasing on top of https://github.com/oneapi-src/unified-memory-framework/pull/176? The failure looks similar to the valgrind failures.

**Comment by ldorau** [comment]
> @ldorau can you try rebasing on top of #176? The failure looks similar to the valgrind failures.

@igchor Done

**Review by PatKamin — APPROVED** [review]

**Review by KFilipek — APPROVED** [review]

**Review by kswiecicki — APPROVED** [review]

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
~~wait for #176 ~~

@ldorau, please rebase

**Comment by ldorau** [comment]
> ~wait for #176~
> 
> @ldorau, please rebase

@lukaszstolarczuk Rebased.
Done

**Pull request merged**
