### PR TITLE
fix for shadowed declaration error

### PR DESCRIPTION
**Pull request by bratpiorka**
fixes for shadowed decl errors when compiled with -Wshadow flag

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
Please describe what problem you want to solve here (I do not understand why this change is needed - it should be explained in the commit message).

**Comment by igchor** [comment]
> Please describe what problem you want to solve here (I do not understand why this change is needed - it should be explained in the commit message).

I guess this is to fix  `-Wshadow` warning but I don't think this flag makes much sense for C++ tbh.

**Comment by bratpiorka** [comment]
@ldorau I updated the commit message

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1:

**Review by igchor — APPROVED** [review]

**Comment by bratpiorka** [comment]
all - I'll try to change cmake options at oneCCL side instead of changing our flags. If I got problems I will re-open this PR

**Pull request closed without merging**
